-- Retro-Gamers.it comment moderation v1.
-- Run manually in Supabase Dashboard -> SQL Editor.
--
-- The project already uses public.comments.status as the comment moderation
-- state. V1 reuses it instead of adding a second moderation_status column:
--   approved -> approved
--   pending_review -> pending
--   rejected -> rejected
--
-- Existing comments remain approved when status is missing.

alter table public.comments
  add column if not exists moderation_reason text null;

alter table public.comments
  add column if not exists moderated_at timestamptz null;

alter table public.comments
  add column if not exists moderated_by uuid null references auth.users(id) on delete set null;

update public.comments
set status = 'approved'
where status is null;

comment on column public.comments.moderation_reason is
  'Short reason generated by comment moderation v1 or the latest manual moderation note.';

comment on column public.comments.moderated_at is
  'Timestamp of the latest automatic or manual moderation decision.';

comment on column public.comments.moderated_by is
  'Moderator user id for the latest manual moderation decision, when available.';

notify pgrst, 'reload schema';
