-- Retro-Gamers.it guest comment identities.
-- Run manually in Supabase Dashboard -> SQL Editor before deploying the
-- frontend guest-comment feature.
--
-- Privacy model:
-- - email addresses are never stored; only a server-generated HMAC is kept;
-- - raw IP addresses are never stored; only a short-lived HMAC may be kept;
-- - public comments contain only the display name and an opaque identity id;
-- - private identity and abuse tables have RLS enabled and no public policies.

create extension if not exists pgcrypto;

create table if not exists public.guest_identities (
  id uuid primary key default gen_random_uuid(),
  email_hmac text not null unique,
  canonical_display_name text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  approved_comments_count integer not null default 0
    check (approved_comments_count >= 0),
  status text not null default 'active'
    check (status in ('active', 'restricted', 'blocked'))
);

comment on table public.guest_identities is
  'Private pseudonymous identities for guest comments. No plaintext email is stored.';
comment on column public.guest_identities.email_hmac is
  'HMAC-SHA256 of the normalized email, generated only by the server runtime.';
comment on column public.guest_identities.canonical_display_name is
  'Stable public name selected on the first accepted guest submission.';

alter table public.guest_identities enable row level security;
revoke all on table public.guest_identities from anon, authenticated;

create index if not exists guest_identities_status_last_seen_idx
  on public.guest_identities (status, last_seen_at desc);

alter table public.comments
  add column if not exists author_type text not null default 'registered';

alter table public.comments
  add column if not exists guest_identity_id uuid null
    references public.guest_identities(id) on delete restrict;

alter table public.comments
  add column if not exists guest_display_name text null;

alter table public.comments
  add column if not exists abuse_flags text[] not null default '{}'::text[];

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'comments_author_type_check'
      and conrelid = 'public.comments'::regclass
  ) then
    alter table public.comments
      add constraint comments_author_type_check
      check (author_type in ('registered', 'guest', 'legacy'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'comments_guest_identity_shape_check'
      and conrelid = 'public.comments'::regclass
  ) then
    alter table public.comments
      add constraint comments_guest_identity_shape_check
      check (
        (
          author_type = 'guest'
          and user_id is null
          and profile_id is null
          and guest_identity_id is not null
          and nullif(btrim(guest_display_name), '') is not null
        )
        or
        (
          author_type <> 'guest'
          and guest_identity_id is null
          and guest_display_name is null
        )
      );
  end if;
end
$$;

comment on column public.comments.author_type is
  'Explicit author source: registered, guest or legacy.';
comment on column public.comments.guest_identity_id is
  'Opaque private identity reference for guest-authored comments.';
comment on column public.comments.guest_display_name is
  'Public stable display name for a guest-authored comment.';
comment on column public.comments.abuse_flags is
  'Non-sensitive moderation flags. Never contains email, IP or their HMAC values.';

create index if not exists comments_guest_identity_created_idx
  on public.comments (guest_identity_id, created_at desc)
  where author_type = 'guest';

create index if not exists comments_author_type_status_created_idx
  on public.comments (author_type, status, created_at desc);

create table if not exists public.guest_comment_events (
  id bigint generated by default as identity primary key,
  guest_identity_id uuid not null
    references public.guest_identities(id) on delete cascade,
  comment_id uuid null
    references public.comments(id) on delete cascade,
  ip_hmac text null,
  body_hmac text not null,
  flags text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

comment on table public.guest_comment_events is
  'Private rate-limit and abuse signals for guest comments; retain for no more than 30 days.';
comment on column public.guest_comment_events.ip_hmac is
  'Optional HMAC-SHA256 of the request IP. Never contains a plaintext network address.';
comment on column public.guest_comment_events.body_hmac is
  'HMAC-SHA256 used only to detect repeated content without retaining another body copy.';

alter table public.guest_comment_events enable row level security;
revoke all on table public.guest_comment_events from anon, authenticated;

create index if not exists guest_comment_events_identity_created_idx
  on public.guest_comment_events (guest_identity_id, created_at desc);

create index if not exists guest_comment_events_ip_created_idx
  on public.guest_comment_events (ip_hmac, created_at desc)
  where ip_hmac is not null;

create index if not exists guest_comment_events_body_created_idx
  on public.guest_comment_events (body_hmac, created_at desc);

create index if not exists guest_comment_events_created_idx
  on public.guest_comment_events (created_at);

create table if not exists public.community_bans (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null
    check (subject_type in ('account', 'guest', 'ip')),
  user_id uuid null references auth.users(id) on delete restrict,
  guest_identity_id uuid null
    references public.guest_identities(id) on delete restrict,
  ip_hmac text null,
  scope text not null default 'comments_community'
    check (scope in ('comments', 'community', 'comments_community')),
  status text not null
    check (status in ('restricted', 'blocked', 'banned')),
  reason text not null
    check (char_length(btrim(reason)) between 3 and 1000),
  expires_at timestamptz null,
  exceptional_permanent_ip boolean not null default false,
  created_at timestamptz not null default now(),
  created_by uuid null references auth.users(id) on delete set null,
  revoked_at timestamptz null,
  revoked_by uuid null references auth.users(id) on delete set null,
  revocation_reason text null,
  constraint community_bans_subject_shape_check check (
    (
      subject_type = 'account'
      and user_id is not null
      and guest_identity_id is null
      and ip_hmac is null
      and status in ('restricted', 'banned')
    )
    or
    (
      subject_type = 'guest'
      and user_id is null
      and guest_identity_id is not null
      and ip_hmac is null
      and status in ('restricted', 'blocked')
    )
    or
    (
      subject_type = 'ip'
      and user_id is null
      and guest_identity_id is null
      and ip_hmac is not null
      and status in ('restricted', 'blocked')
      and (expires_at is not null or exceptional_permanent_ip)
    )
  ),
  constraint community_bans_revocation_shape_check check (
    (revoked_at is null and revoked_by is null)
    or revoked_at is not null
  )
);

comment on table public.community_bans is
  'Private, scoped moderation restrictions. IP HMAC is supplementary and is never the primary account or guest identity.';
comment on column public.community_bans.reason is
  'Internal moderation reason. It must never be exposed by public comment APIs.';
comment on column public.community_bans.exceptional_permanent_ip is
  'Explicit marker required for an exceptional manually approved permanent IP block.';

alter table public.community_bans enable row level security;
revoke all on table public.community_bans from anon, authenticated;

create index if not exists community_bans_account_active_idx
  on public.community_bans (user_id, created_at desc)
  where subject_type = 'account' and revoked_at is null;

create index if not exists community_bans_guest_active_idx
  on public.community_bans (guest_identity_id, created_at desc)
  where subject_type = 'guest' and revoked_at is null;

create index if not exists community_bans_ip_active_idx
  on public.community_bans (ip_hmac, created_at desc)
  where subject_type = 'ip' and revoked_at is null;

create table if not exists public.community_ban_events (
  id bigint generated by default as identity primary key,
  ban_id uuid null references public.community_bans(id) on delete set null,
  event_type text not null check (event_type in ('created', 'revoked')),
  subject_type text not null check (subject_type in ('account', 'guest', 'ip')),
  user_id uuid null,
  guest_identity_id uuid null,
  ip_hmac text null,
  scope text not null,
  status text not null,
  reason text not null,
  expires_at timestamptz null,
  moderator_id uuid null,
  created_at timestamptz not null default now(),
  constraint community_ban_events_subject_shape_check check (
    (
      subject_type = 'account'
      and user_id is not null
      and guest_identity_id is null
      and ip_hmac is null
    )
    or
    (
      subject_type = 'guest'
      and user_id is null
      and guest_identity_id is not null
      and ip_hmac is null
    )
    or
    (
      subject_type = 'ip'
      and user_id is null
      and guest_identity_id is null
      and ip_hmac is not null
    )
  )
);

comment on table public.community_ban_events is
  'Immutable private audit log for restriction creation and revocation.';

alter table public.community_ban_events enable row level security;
revoke all on table public.community_ban_events from anon, authenticated;

create index if not exists community_ban_events_subject_created_idx
  on public.community_ban_events (subject_type, created_at desc);

create index if not exists community_ban_events_ban_created_idx
  on public.community_ban_events (ban_id, created_at desc);

create or replace function public.audit_community_ban_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.community_ban_events (
      ban_id,
      event_type,
      subject_type,
      user_id,
      guest_identity_id,
      ip_hmac,
      scope,
      status,
      reason,
      expires_at,
      moderator_id
    )
    values (
      new.id,
      'created',
      new.subject_type,
      new.user_id,
      new.guest_identity_id,
      new.ip_hmac,
      new.scope,
      new.status,
      new.reason,
      new.expires_at,
      new.created_by
    );
  elsif old.revoked_at is null and new.revoked_at is not null then
    insert into public.community_ban_events (
      ban_id,
      event_type,
      subject_type,
      user_id,
      guest_identity_id,
      ip_hmac,
      scope,
      status,
      reason,
      expires_at,
      moderator_id
    )
    values (
      new.id,
      'revoked',
      new.subject_type,
      new.user_id,
      new.guest_identity_id,
      new.ip_hmac,
      new.scope,
      new.status,
      coalesce(nullif(btrim(new.revocation_reason), ''), new.reason),
      new.expires_at,
      new.revoked_by
    );
  end if;

  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'audit_community_ban_change'
      and tgrelid = 'public.community_bans'::regclass
      and not tgisinternal
  ) then
    execute $trigger$
      create trigger audit_community_ban_change
      after insert or update on public.community_bans
      for each row
      execute function public.audit_community_ban_change()
    $trigger$;
  end if;
end
$$;

revoke all on function public.audit_community_ban_change() from public;

create or replace function public.purge_expired_guest_comment_events()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count bigint;
begin
  delete from public.guest_comment_events
  where created_at < now() - interval '30 days';

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

comment on function public.purge_expired_guest_comment_events() is
  'Deletes private guest abuse signals older than 30 days. The frontend also invokes equivalent cleanup on guest submissions.';

revoke all on function public.purge_expired_guest_comment_events() from public;

create or replace function public.purge_expired_ip_moderation_records()
returns table (events_deleted bigint, bans_deleted bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  removed_events bigint;
  removed_bans bigint;
begin
  delete from public.community_ban_events
  where subject_type = 'ip'
    and created_at < now() - interval '90 days';
  get diagnostics removed_events = row_count;

  delete from public.community_bans
  where subject_type = 'ip'
    and (
      (revoked_at is not null and revoked_at < now() - interval '90 days')
      or
      (expires_at is not null and expires_at < now() - interval '90 days')
    );
  get diagnostics removed_bans = row_count;

  return query select removed_events, removed_bans;
end;
$$;

comment on function public.purge_expired_ip_moderation_records() is
  'Deletes expired or revoked pseudonymous IP moderation records after a 90-day technical retention period.';

revoke all on function public.purge_expired_ip_moderation_records() from public;

create or replace function public.sync_guest_approved_comment_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_is_approved boolean := false;
  new_is_approved boolean := false;
  target_identity_id uuid;
begin
  if tg_op <> 'INSERT' then
    old_is_approved :=
      old.author_type = 'guest' and old.status = 'approved' and old.deleted_at is null;
  end if;

  if tg_op <> 'DELETE' then
    new_is_approved :=
      new.author_type = 'guest' and new.status = 'approved' and new.deleted_at is null;
  end if;

  if old_is_approved = new_is_approved then
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  target_identity_id := case
    when tg_op = 'DELETE' then old.guest_identity_id
    else coalesce(new.guest_identity_id, old.guest_identity_id)
  end;

  update public.guest_identities
  set approved_comments_count = greatest(
    0,
    approved_comments_count + case when new_is_approved then 1 else -1 end
  )
  where id = target_identity_id;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'sync_guest_approved_comment_count'
      and tgrelid = 'public.comments'::regclass
      and not tgisinternal
  ) then
    execute $trigger$
      create trigger sync_guest_approved_comment_count
      after insert or update or delete on public.comments
      for each row
      execute function public.sync_guest_approved_comment_count()
    $trigger$;
  end if;
end
$$;

revoke all on function public.sync_guest_approved_comment_count() from public;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant all on table
      public.guest_identities,
      public.guest_comment_events,
      public.community_bans,
      public.community_ban_events
    to service_role;

    grant usage, select on all sequences in schema public to service_role;

    grant execute on function public.purge_expired_guest_comment_events()
      to service_role;
    grant execute on function public.purge_expired_ip_moderation_records()
      to service_role;
  end if;
end
$$;

notify pgrst, 'reload schema';
